monubit_recommendation:
    resource: "@MonubitRecommendationBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_tag:
    resource: "@MonubitTagBundle/Controller/"
    type:     annotation
    prefix:   /
    
monubit_ratings:
    resource: "@MonubitRatingsBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine

monubit_user:
    resource: "@MonubitUserBundle/Resources/config/routing.yml"

monubit_search:
    resource: "@MonubitSearchBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_front:
    resource: "@MonubitFrontBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_monument:
    resource: "@MonubitMonumentBundle/Controller/"
    type:     annotation
    prefix:   /
