monubit_front:
    resource: "@MonubitFrontBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_monument:
    resource: "@MonubitMonumentBundle/Controller/"
    type:     annotation
    prefix:   /

