#monubit_ratings:
#    resource: "@MonubitRatingsBundle/Controller/"
#    type:     annotation
#    prefix:   /

monubit_user:
    resource: "@MonubitUserBundle/Resources/config/routing.yml"

monubit_search:
    resource: "@MonubitSearchBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_front:
    resource: "@MonubitFrontBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_monument:
    resource: "@MonubitMonumentBundle/Controller/"
    type:     annotation
    prefix:   /

