monubit_user:
    resource: "@MonubitUserBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_search:
    resource: "@MonubitSearchBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_front:
    resource: "@MonubitFrontBundle/Controller/"
    type:     annotation
    prefix:   /

monubit_monument:
    resource: "@MonubitMonumentBundle/Controller/"
    type:     annotation
    prefix:   /

