parameters:
#    monubit_user.example.class: Monubit\UserBundle\Example

services:
#    monubit_user.example:
#        class: %monubit_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
